import { ToastContainer } from "react-toastify";
import "./globals.css";
import Navbar from "./Navbar";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { ourFileRouter } from "./api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
import Head from "next/head";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "DEPO Coffee",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Next App</title>
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <body>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        {children}
      </body>
    </html>
  );
}
